Log feedback form submissions in Google sheets
NeuroBridge/Search-Portal pull request #66
Opened 2023-03-30 20:51 UTC by mbwatson

this PR handles communicating with Google Sheets via an Apps Script script upon Feedback Form submission.

@Woozl i'd appreciate a general sanity check on the decisions i've made when implementing this

2023-03-31 17:25 UTC, Woozl requested changes

2023-03-31 17:25 UTC, Woozl commented on src/styles/index.css
> +  display: none;
This actually disables the spam checking:

https://stackoverflow.com/a/53986985

2023-03-31 19:05 UTC, mbwatson commented on src/styles/index.css
> +  display: none;
thank you!

2023-04-11 17:54 UTC, Woozl approved these changes

2023-04-14 18:11 UTC, merged